### ISSUE TITLE
if this addons can show video no a movies?

### ISSUE THREAD

**Issue by ericvlog** [vanchaxy/plexio#18]
it can show based on library ?

or just shows 2 catalog "movies","tvshow"

and can it show catalog no have imdb id, or no even a movies, example just a video for playback.

Thank regard.

**Comment by vanchaxy** [comment]
Addon can show any movies or series library from Plex. For each Plex library, it will show the catalog in Stremio. You can use this Stremio catalog to open files not matched with IMDB. Stremio search also works for catalogs. Matched IMDB is required to use other addons catalogs.
