### ISSUE TITLE
Security Alert Another device is attempting to sign in..

### ISSUE THREAD

**Issue by Wateraga** [vanchaxy/plexio#22]
I get the warning 

"Security Alert
Another device is attempting to sign in using your Plex account. You should only continue if you know this device and intend to grant it access."

The login is from central Europ and I am definitely not located there.

I only get this warning when clicking the link from this Github. 

Is there a reason for this?

**Comment by vanchaxy** [comment]
Yes, the login process is handled by the backend which is located in Europe/US and routed based on load/location. I'm working on the new fronted that will handle login locally but it won't make it more secure, just will get rid of the warning.
