### ISSUE TITLE
series can , but movies cannot found stream on stremio

### ISSUE THREAD

**Issue by ericvlog** [vanchaxy/plexio#25]
Hello, i install using your url....series working great , but all movies stremio unable to found link in plex.

thanks

**Comment by ericvlog** [comment]
below screenshot is my installation id.

![image](https://github.com/user-attachments/assets/9ce2106d-9a44-4e4f-b3d0-6c10bb466c02)

tq

**Comment by vanchaxy** [comment]
Can you see plexio catalog on the discover page?

**Comment by vanchaxy** [comment]
Please, reinstall the addon. If the problem persists kindly create a discussion in the discord support channel with the new installation ID.
