### ISSUE TITLE
Won't install, "The string to be encoded contains characters outside of the Latin1 range."

### ISSUE THREAD

**Issue by knosuhor** [vanchaxy/plexio#26]
Plugin won't install after choosing options and testing successfully.
Error in console:
<img width="963" alt="image" src="https://github.com/user-attachments/assets/56290253-fc99-4f59-b7ae-841130324d9c">
Tried few browsers, on windows and android.

**Comment by vanchaxy** [comment]
What is your server name? It looks like some characters in it can't be encoded in base64.

**Comment by knosuhor** [comment]
Sorry, indeed my server name was the problem. 
Not related to previous question, I managed to see plex libraries but not streams. Would double-nat prevent using plugin for local use? I got error in remote access in plex server (despite which I previously had no problem streaming neither locally nor remotely to plex app on android).

**Comment by vanchaxy** [comment]
Your Plex library stream should be matched using IMDb. If they are and still are not showing in Stremio, share your installation ID.

**Comment by knosuhor** [comment]
If you mean matching by searching IMDb Id number, I did that.  Installation Id is dd57a30b-307a-4af1-95cc-cbe68336adff. Don't know if that matters for when you check my configuration but I do not have Plex server running, when not using it.

**Comment by vanchaxy** [comment]
Please, reinstall the addon. If the problem persists kindly create a discussion in the discord support channel with the new installation ID.

**Comment by knosuhor** [comment]
Thanks! New version works fine.
