### ISSUE TITLE
Ability to hide library catalogs

### ISSUE THREAD

**Issue by R4st3rEyez** [vanchaxy/plexio#30]
Hello, 

It'd be great to have the ability to hide the library catalogs from Home/Discover/Search. You may want to show server content as a source without adding additional rows in these sections.

**Comment by vanchaxy** [comment]
You can select what catalogs to show when installing the addon. Current validation requires you to select at least one (to prevent users from missing this config section). Addon always shows you sources from all libraries. Be aware that addon catalogs are the only way to access media without matched IMDB (like local or plex videos).

**Comment by vanchaxy** [comment]
catalogs are optional now
