### ISSUE TITLE
Only available transcode stream is 480p

### ISSUE THREAD

**Issue by R4st3rEyez** [vanchaxy/plexio#31]
I currently have "Include Transcoded Streams with Lower Resolutions" with only 1080p selected. However, in Stremio, the only transcode option i see is labeled "Transcode 480p" instead of 1080p

**Comment by vanchaxy** [comment]
thank you for the report, it's fixed now. https://github.com/vanchaxy/plexio/commit/3d5215a5eeab67adf79ea935125d7c7ada24f62b Please, reinstall the addon.
