### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by derrgoo** [vanchaxy/plexio#32]
I have received a few error codes. Not sure what is causing these.  ![image](https://github.com/user-attachments/assets/4ecb6003-db89-4f18-a9ab-9b0d3a284532)

**Comment by vanchaxy** [comment]
provide installation id and describe what you are trying to do (step by step)

**Comment by derrgoo** [comment]
Your installation ID: 00473f2e-db16-499d-a0-23d0264d175b

I was just watching a movie and this happens suddenly and I have to close and open and happed again.

**Comment by derrgoo** [comment]
If plex server is the cause it never did when I used plex app.  Anyway I can just restart stream. Thanks for looking

**Comment by derrgoo** [comment]
I reinstalled all my plex libraries and tested with plex app and kodi plex integration with umbrella. Seems to work but stremio I still can't get it to play longer than like 10-20 min until it pulls that error. I even tried different players with stremio. Still the same. Not sure what to fix on my plex setup. Have a great x MAs. Thanks if you have any thoughts.

**Comment by vanchaxy** [comment]
The only known issue that causes this is using direct stream together with plex relay. Addon just provide links from your server to stremio. No calls are made to the addon during streaming
