### ISSUE TITLE
Please let us choose quality/s in the configure page

### ISSUE THREAD

**Issue by jinstan101** [vanchaxy/plexio#6]
As the title suggest.
It hides other sources from appearing because of the transcode qualities.
Also an option to hide catalog of it since cinemeta handles it for me.
Thanks for making the addon possible.

**Comment by vanchaxy** [comment]
Hi, that's planned at some point in the future—both choosing qualities and catalogs to display. However, I didn't understand what you meant by "It hides other sources from appearing because of the transcode qualities." Can you clarify that part for me?

**Comment by vanchaxy** [comment]
Be aware that for Cinemeta catalogs to work, you need your media to be matched in Plex with the correct IMDb. Catalogs guarantee that if your media is not matched or matched incorrectly, you will still be able to play it in Stremio.

**Comment by jinstan101** [comment]
> Hi, that's planned at some point in the future—both choosing qualities and catalogs to display. However, I didn't understand what you meant by "It hides other sources from appearing because of the transcode qualities." Can you clarify that part for me?

Its just it has many qualities shown that it requires to scroll to the end of it so I can choose another source.

**Comment by vanchaxy** [comment]
Done in today release
