### ISSUE TITLE
Frontend only showing a white page with "loading..."

### ISSUE THREAD

**Issue by DustyTurtleDip** [vanchaxy/plexio#8]
Frontend only showing a white page with "loading..."
![image](https://github.com/vanchaxy/plexio/assets/38813688/061a4a7c-f227-4de8-b0c8-0171a8879b8d)

Backend logs : 
backend-1  | INFO:     Will watch for changes in these directories: ['/app']
backend-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
backend-1  | INFO:     Started reloader process [1] using StatReload
backend-1  | INFO:     Started server process [8]
backend-1  | INFO:     Waiting for application startup.
backend-1  | INFO:     Application startup complete.

Frontend logs : 
frontend-1  | 
frontend-1  | > frontend@0.1.0 start
frontend-1  | > react-scripts start
frontend-1  | 
frontend-1  | Browserslist: caniuse-lite is outdated. Please run:
frontend-1  |   npx update-browserslist-db@latest
frontend-1  |   Why you should do it regularly: https://github.com/browserslist/update-db#readme
frontend-1  | (node:25) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
frontend-1  | (Use `node --trace-deprecation ...` to show where the warning was created)
frontend-1  | (node:25) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
frontend-1  | Starting the development server...
frontend-1  | 
frontend-1  | One of your dependencies, babel-preset-react-app, is importing the
frontend-1  | "@babel/plugin-proposal-private-property-in-object" package without
frontend-1  | declaring it in its dependencies. This is currently working because
frontend-1  | "@babel/plugin-proposal-private-property-in-object" is already in your
frontend-1  | node_modules folder for unrelated reasons, but it may break at any time.
frontend-1  | 
frontend-1  | babel-preset-react-app is part of the create-react-app project, which
frontend-1  | is not maintianed anymore. It is thus unlikely that this bug will
frontend-1  | ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
frontend-1  | your devDependencies to work around this error. This will make this message
frontend-1  | go away.
frontend-1  |   
frontend-1  | Compiled successfully!
frontend-1  | 
frontend-1  | You can now view frontend in the browser.
frontend-1  | 
frontend-1  |   Local:            http://localhost:3000
frontend-1  |   On Your Network:  http://172.24.0.4:3000
frontend-1  | 
frontend-1  | Note that the development build is not optimized.
frontend-1  | To create a production build, use npm run build.
frontend-1  | 
frontend-1  | webpack compiled successfully
frontend-1  | Compiling...
frontend-1  | Compiled successfully!
frontend-1  | webpack compiled successfully

Redis logs : 
redis-1  | 1:C 09 Feb 2024 13:14:51.693 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-1  | 1:C 09 Feb 2024 13:14:51.693 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1  | 1:C 09 Feb 2024 13:14:51.693 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1  | 1:C 09 Feb 2024 13:14:51.693 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1  | 1:M 09 Feb 2024 13:14:51.693 * monotonic clock: POSIX clock_gettime
redis-1  | 1:M 09 Feb 2024 13:14:51.693 * Running mode=standalone, port=6379.
redis-1  | 1:M 09 Feb 2024 13:14:51.694 * Server initialized
redis-1  | 1:M 09 Feb 2024 13:14:51.694 * Ready to accept connections tcp

Plex Logs :
plex-1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
plex-1  | [s6-init] ensuring user provided files have correct perms...exited 0.
plex-1  | [fix-attrs.d] applying ownership & permissions fixes...
plex-1  | [fix-attrs.d] done.
plex-1  | [cont-init.d] executing container initialization scripts...
plex-1  | [cont-init.d] 40-plex-first-run: executing... 
plex-1  | Creating pref shell
plex-1  | Plex Media Server first run setup complete
plex-1  | [cont-init.d] 40-plex-first-run: exited 0.
plex-1  | [cont-init.d] 45-plex-hw-transcode-and-connected-tuner: executing... 
plex-1  | [cont-init.d] 45-plex-hw-transcode-and-connected-tuner: exited 0.
plex-1  | [cont-init.d] 50-plex-update: executing... 
plex-1  | [cont-init.d] 50-plex-update: exited 0.
plex-1  | [cont-init.d] done.
plex-1  | [services.d] starting services
plex-1  | Starting Plex Media Server.
plex-1  | [services.d] done.

There is no documentation / Or maybe I didn't find it ? 

Am I missing something ?

**Comment by vanchaxy** [comment]
There is no documentation or self-hosting support yet. Probably, the problem is that the frontend can't connect to the backend or something related. For now, it's recommended to use the hosted version [here](https://plexio.stream/).
